-- 0038: enrich the Caterina menu — reparti (Cucina/Bar/Rosticceria/Pokeria), etichette,
-- tempo di preparazione, scorte random (5-25), and a photo for EVERY product.
-- UPDATE migration (the rows already exist from 0037); idempotent; safe in prod.

update public.restaurants set
  reparti = '[{"id": "cucina", "nome": "Cucina", "colore": "#d97706"}, {"id": "rosticceria", "nome": "Rosticceria", "colore": "#dc2626"}, {"id": "pokeria", "nome": "Pokeria", "colore": "#16a34a"}, {"id": "bar", "nome": "Bar", "colore": "#2563eb"}]'::jsonb,
  etichette = '["Consigliato", "Vegetariano", "Vegano", "Piccante", "Pesce crudo", "Alcolico", "Analcolico"]'::jsonb,
  funzionalita = coalesce(funzionalita, '{}'::jsonb) || '{"etichette": true, "reparto": true, "scorte": true, "tempo_stimato": true, "attesa_stimata": true, "piatto_consigliato": true}'::jsonb
where id = '2a92ceb7-ce3a-5ef0-83b6-54953df2a50d';

update public.menu_items set reparto = 'cucina', tempo_preparazione = 8, scorta = 10, etichette = '[]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/uova-bacon.webp') where id = '59e6acd1-2bd8-5e85-996d-e3c26ca8d04a';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 8, scorta = 16, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/pancake-sciroppo-d_acero-frutti-bosco.webp') where id = '1436a722-ae7e-5562-baec-1c4f07676dd5';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 8, scorta = 15, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/pancake-sciroppo-acero-fragole.webp') where id = '530ad6f0-f840-5775-ae06-f53c367ffa46';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 8, scorta = 17, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/colazione-pancake-cioccolatobiancoefruttidibosco.webp') where id = '956f8d74-a7f4-54b6-9ca4-db819cb27d2e';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 8, scorta = 12, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/colazione-img.webp') where id = 'e648f8cf-1f2b-5994-8c61-2643913a63d0';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 8, scorta = 17, etichette = '[]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/avocado-toast.webp') where id = 'ee0a1d72-ccb4-5c28-836b-85b6a07f5b62';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 8, scorta = 21, etichette = '[]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/toast.webp') where id = 'e1b08af4-a967-5bee-96dc-0638a6bdbc33';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 8, scorta = 9, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/colazione-frenchtoast.webp') where id = 'c4e4e05b-9044-592e-8e0e-a93518898be7';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 8, scorta = 24, etichette = '["Vegetariano", "Consigliato"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/caciocavallo-piastra-img.jpg') where id = '7a342bcb-84a1-5f97-8ec1-16a3980f5518';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 8, scorta = 19, etichette = '[]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/classico.webp') where id = '6406fa5b-c786-5ab1-aeb1-7a497418425c';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 8, scorta = 23, etichette = '[]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/secondi-polpette-al-sugo.webp') where id = 'a8ce7619-9651-564f-b83e-57c531f467cb';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 14, scorta = 15, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/ristorante-orecchietteallarrabbiata.webp') where id = '6ba3f100-11ea-5e05-ac2a-b5b91a21fca3';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 14, scorta = 12, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/primi-img.webp') where id = '8915a7d2-32dc-568a-909d-e4a9e98092ea';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 14, scorta = 7, etichette = '["Consigliato"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/primi-img.webp') where id = 'cf1a6a81-9603-5fb8-9ccc-dd7370a95234';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 14, scorta = 21, etichette = '[]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/primi-fusilli-alla-siciliana-1.webp') where id = '85e6754f-4585-5e62-b554-3a6e282ccf3d';
update public.menu_items set reparto = 'rosticceria', tempo_preparazione = 18, scorta = 16, etichette = '[]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/Copia-di-milanese.webp') where id = 'c178d17b-141e-5f07-993a-0c3e31ae98be';
update public.menu_items set reparto = 'rosticceria', tempo_preparazione = 18, scorta = 18, etichette = '[]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/salmone.png') where id = '7fce9f26-c866-5650-9193-cfa82c66d132';
update public.menu_items set reparto = 'rosticceria', tempo_preparazione = 18, scorta = 7, etichette = '[]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/img-tuna-teriaki.png') where id = '653f7ddf-d448-55ed-abe8-d031359cec4a';
update public.menu_items set reparto = 'rosticceria', tempo_preparazione = 18, scorta = 14, etichette = '["Consigliato"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/secondi-cat-img.webp') where id = '5fe28586-a60e-5dfa-a270-a928db09d704';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 6, scorta = 5, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/contorni-img.webp') where id = 'ac79212b-1b0f-53a3-aa11-5cc45f6bfb0a';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 6, scorta = 8, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/contorni-img.webp') where id = 'ef9d4f4e-d98a-55b2-b971-de2eb36354ba';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 6, scorta = 17, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/contorni-img.webp') where id = '22d30154-1154-5e85-a0c4-e6abc6b312fe';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 6, scorta = 7, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/contorni-img.webp') where id = '41f72d80-6fb8-52b2-8b63-a22b8a16b732';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 4, scorta = 20, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/dolci-img.webp') where id = 'ad77c074-fc16-5e40-8338-e78af7b1ba54';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 4, scorta = 8, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/dolci-img.webp') where id = 'b5cc8a43-d05f-5260-a653-3bb623509320';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 4, scorta = 25, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/dolci-img.webp') where id = '81d7d876-e7f8-56e6-a012-be8c366df86c';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 4, scorta = 16, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/dolci-img.webp') where id = '7168c82f-c767-58e3-874a-9c8c73739705';
update public.menu_items set reparto = 'cucina', tempo_preparazione = 4, scorta = 11, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/dolci-img.webp') where id = '8810195a-fc5e-5a5e-a006-27a757c8e5cc';
update public.menu_items set reparto = 'rosticceria', tempo_preparazione = 6, scorta = 5, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/panino-caprese-1.webp') where id = '2b5c1899-a762-5e0d-91c7-c8d855ec155a';
update public.menu_items set reparto = 'rosticceria', tempo_preparazione = 6, scorta = 19, etichette = '[]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/panino-classico-2.webp') where id = '218c5f83-589b-5f51-9b69-c34ac3a13a1c';
update public.menu_items set reparto = 'rosticceria', tempo_preparazione = 6, scorta = 16, etichette = '[]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/panino-mediterraneo-2.webp') where id = 'c373ea80-04a8-592e-b0f2-da36f11bbc97';
update public.menu_items set reparto = 'pokeria', tempo_preparazione = 9, scorta = 17, etichette = '["Consigliato"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/poke-meditterasia.webp') where id = '0176b5eb-c28d-5a13-a673-80df40f9a9ad';
update public.menu_items set reparto = 'pokeria', tempo_preparazione = 9, scorta = 17, etichette = '["Pesce crudo"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/salmone.png') where id = '28c8aa19-20fa-5b55-8197-7c3870d7199f';
update public.menu_items set reparto = 'pokeria', tempo_preparazione = 9, scorta = 19, etichette = '[]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/poke-fritto-gustoso.webp') where id = '25d6d547-74ec-587c-b395-bd51a9bb7096';
update public.menu_items set reparto = 'pokeria', tempo_preparazione = 9, scorta = 12, etichette = '[]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/poke-leggero.webp') where id = '3c72f62a-aafe-528e-b43e-dc98459d5433';
update public.menu_items set reparto = 'pokeria', tempo_preparazione = 9, scorta = 14, etichette = '["Pesce crudo"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/img-tuna-teriaki.png') where id = '9b3fbd29-5851-5330-a67b-6700a43331b1';
update public.menu_items set reparto = 'pokeria', tempo_preparazione = 9, scorta = 8, etichette = '["Piccante"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/gambero.png') where id = 'e1aca4d2-d454-5d30-bf6f-8864212c4327';
update public.menu_items set reparto = 'pokeria', tempo_preparazione = 9, scorta = 24, etichette = '["Vegetariano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/Copia-di-bowl-1.webp') where id = '11ff75b7-b856-5463-ae46-839ee01907f7';
update public.menu_items set reparto = 'pokeria', tempo_preparazione = 9, scorta = 15, etichette = '["Vegano"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/componi-poke-img.webp') where id = '8a520c7a-a632-5281-bc58-43ea7d74bfac';
update public.menu_items set reparto = 'pokeria', tempo_preparazione = 9, scorta = 17, etichette = '[]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/componi-poke-img.webp') where id = '99561558-f4be-5a89-baf8-77c744bc38c7';
update public.menu_items set reparto = 'bar', tempo_preparazione = 2, scorta = 19, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/birre-cat-img.webp') where id = 'a321fa7f-ae22-5645-afaf-2ce4e9872313';
update public.menu_items set reparto = 'bar', tempo_preparazione = 2, scorta = 17, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/birre-cat-img.webp') where id = '3fb8eb59-f762-5ac4-b102-d6ef6f8ade47';
update public.menu_items set reparto = 'bar', tempo_preparazione = 2, scorta = 19, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/birre-cat-img.webp') where id = 'eaeb73ec-e6e9-5a7f-89cd-88d815ce72bb';
update public.menu_items set reparto = 'bar', tempo_preparazione = 2, scorta = 15, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/birre-cat-img.webp') where id = 'afd65794-916c-5125-a82b-5d4c0c3ef08c';
update public.menu_items set reparto = 'bar', tempo_preparazione = 2, scorta = 14, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/birre-cat-img.webp') where id = 'a2392d97-12ef-56c1-8678-026f2ac93539';
update public.menu_items set reparto = 'bar', tempo_preparazione = 4, scorta = 15, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/cocktails-cat-img-1.webp') where id = 'd7f97035-cc10-536d-9cc0-961dd41770cd';
update public.menu_items set reparto = 'bar', tempo_preparazione = 4, scorta = 13, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/cocktails-cat-img-1.webp') where id = 'bc92206c-cd46-5d49-ade1-75c82fba0404';
update public.menu_items set reparto = 'bar', tempo_preparazione = 4, scorta = 10, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/cocktails-cat-img-1.webp') where id = '843e255b-7e92-52aa-a1c9-f4001b2bd298';
update public.menu_items set reparto = 'bar', tempo_preparazione = 4, scorta = 6, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/cocktails-cat-img-1.webp') where id = 'b1e1a692-b148-594b-9bb0-68641320bf91';
update public.menu_items set reparto = 'bar', tempo_preparazione = 4, scorta = 9, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/cocktails-cat-img-1.webp') where id = 'f1f3cdb5-1062-536d-935a-1564ae9fcdc2';
update public.menu_items set reparto = 'bar', tempo_preparazione = 4, scorta = 17, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/cocktails-cat-img-1.webp') where id = '8ac11c66-c3b1-50e9-994d-21de509b187c';
update public.menu_items set reparto = 'bar', tempo_preparazione = 4, scorta = 15, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/cocktails-cat-img-1.webp') where id = '45eeb17b-ddde-567b-bdde-c89fcdcae50c';
update public.menu_items set reparto = 'bar', tempo_preparazione = 4, scorta = 14, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/cocktails-cat-img-1.webp') where id = '06445adf-fc83-5f9e-a492-ecb19bc12ab3';
update public.menu_items set reparto = 'bar', tempo_preparazione = 4, scorta = 24, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/cocktails-cat-img-1.webp') where id = '7df9be33-d8bd-5061-a7d2-5ffb701211a4';
update public.menu_items set reparto = 'bar', tempo_preparazione = 4, scorta = 20, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/cocktails-cat-img-1.webp') where id = 'ea80b661-4886-5196-92af-08721ae990c1';
update public.menu_items set reparto = 'bar', tempo_preparazione = 4, scorta = 23, etichette = '["Alcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/cocktails-cat-img-1.webp') where id = '89fb9a5e-1257-5138-bf2e-0dbee2a7b386';
update public.menu_items set reparto = 'bar', tempo_preparazione = 2, scorta = 13, etichette = '["Analcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/soft-drinks-cat-img.webp') where id = '31dfdf07-1ba4-52cc-9a0f-695819980be1';
update public.menu_items set reparto = 'bar', tempo_preparazione = 2, scorta = 15, etichette = '["Analcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/soft-drinks-cat-img.webp') where id = 'acdb78a0-3cbf-5823-88fc-f93fa695227b';
update public.menu_items set reparto = 'bar', tempo_preparazione = 2, scorta = 8, etichette = '["Analcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/soft-drinks-cat-img.webp') where id = '8f9c61b2-1ef1-5c15-b14e-d24d95916c13';
update public.menu_items set reparto = 'bar', tempo_preparazione = 2, scorta = 9, etichette = '["Analcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/soft-drinks-cat-img.webp') where id = '3441b329-a3df-59ef-96fe-6f89a285f37c';
update public.menu_items set reparto = 'bar', tempo_preparazione = 2, scorta = 21, etichette = '["Analcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/soft-drinks-cat-img.webp') where id = '8548e52e-a13a-5224-b900-8a40cfc01cb9';
update public.menu_items set reparto = 'bar', tempo_preparazione = 2, scorta = 9, etichette = '["Analcolico"]'::jsonb, foto_url = coalesce(foto_url, '/menu/caterina/soft-drinks-cat-img.webp') where id = 'b3cfe113-520b-5991-b9ed-6cc2ff1c6d33';
